### ISSUE TITLE
请教关于png压缩成文件，如果进行递归减少文件的size

### ISSUE THREAD

**Issue by guqun** [crazecoder/flutter_luban#13]
您好！
请教一下，这段代码是如何通过递归减少文件size的，level这个参数的作用是什么？
谢谢指点
`  static void _compressPng({
    Image image,
    File file,
    level: 9,
    targetSize,
  }) {
    var im = encodePng(image, level: level);
    var tempImageSize = Uint8List.fromList(im).lengthInBytes;
    if (tempImageSize / 1024 < targetSize) {
      _small2LargeCompressImage(
        image: image,
        file: file,
        targetSize: targetSize,
        isJpg: false,
      );
      return;
    }
    file.writeAsBytesSync(im);
  }
}`

**Comment by crazecoder** [comment]
我的理解是和quality效果一样，想要具体了解可以去[image](https://github.com/brendan-duncan/image)库看看
