### ISSUE TITLE
Compress multiple files

### ISSUE THREAD

**Issue by saelco** [crazecoder/flutter_luban#14]
I have list of files like (sample1.jpg, sample2.jpg, sample3.jpg, ...). I want to compress those files before upload it. I plan to use Dio to upload it. Can you help me the code to do that?

**Comment by crazecoder** [comment]
https://github.com/crazecoder/flutter_luban/commit/cd5bc06ae5748497e38f806b1544eaff2a70614d
This may help you

**Comment by saelco** [comment]
work like a charm. thank you
