### ISSUE TITLE
Compressed image aspect ratio problem

### ISSUE THREAD

**Issue by saelco** [crazecoder/flutter_luban#15]
I compressed an image but the aspect ratio of compressed image changed like it. How fix the problem?

![Capture+_2019-12-10-10-21-30](https://user-images.githubusercontent.com/26133725/70492399-e442fa00-1b36-11ea-96eb-dc92a639d8ec.png)

**Comment by crazecoder** [comment]
What are the details of this picture? Such as resolution and size

**Comment by saelco** [comment]
![Screenshot_2019-12-10-13-12-41](https://user-images.githubusercontent.com/26133725/70500822-03e61c80-1b4f-11ea-8b67-9eb1977aa9cd.png)

**Comment by crazecoder** [comment]
I have found several similar pictures, but they all work well. Could you please send me the original pictures? If you don't mind, I'll debug it again

**Comment by saelco** [comment]
https://drive.google.com/file/d/1F6f35e63j-uTYL3Ty3E8x-cEcsiFocu7/view?usp=drivesdk

**Comment by crazecoder** [comment]
599cdd82ab56331dabc33f9f591e9bac0a52e3d8
Try again, I think it may be after the image has been edited, but the read resolution is still the original image, so this caused the problem

**Comment by crazecoder** [comment]
599cdd82ab56331dabc33f9f591e9bac0a52e3d8
Try again, I think it may be after the image has been edited, but the read resolution is still the original image, so this caused the problem

**Comment by saelco** [comment]
It works! Thank you
![Screenshot_2019-12-10-22-35-14](https://user-images.githubusercontent.com/26133725/70543743-78e04300-1b9d-11ea-985a-a4a734d286a0.png)
