### ISSUE TITLE
I get this error after upgrading flutter to latest version 1.12.13+hotfix.5

### ISSUE THREAD

**Issue by soile1991** [crazecoder/flutter_luban#17]
Flutter 1.12.13+hotfix.5 • channel stable 

Because every version of flutter_test from sdk depends on image 2.1.4 and flutter_luban 0.1.9+2 depends on image ^2.1.9, flutter_test from sdk is incompatible with flutter_luban 0.1.9+2.

**Comment by crazecoder** [comment]
https://github.com/flutter/flutter/issues/21338

**Comment by dulumao** [comment]
+1

**Comment by kossfun** [comment]
+1

**Comment by badboy-tian** [comment]
+1

**Comment by badboy-tian** [comment]
```
➜  ~ flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.15.2 19C57, locale
    zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] Connected device (4 available)

• No issues found!

```

**Comment by crazecoder** [comment]
The simplest solution is to remove flutter_test

**Comment by soile1991** [comment]
> The simplest solution is to remove flutter_test

That’s no solution some of us including myself use flutter test to perform unit testing etc on CI pipelines

**Comment by crazecoder** [comment]
https://github.com/brendan-duncan/image/issues/182
@soile1991 It's a flutter_test issue. Also, without flutter_test, I think you can do a unit test with the test in flutter_luban

**Comment by nilsreichardt** [comment]
+1

**Comment by simanlx** [comment]
修改flutter下 flutter_test  依赖版本就行了啊

**Comment by zhongxinqiang** [comment]
直接注释掉pubspec.yaml文件中dev_dependencies下面的flutter_test就可以了：
```
dev_dependencies:
#  flutter_test:
#    sdk: flutter
```
