### ISSUE TITLE
Compiler message:

### ISSUE THREAD

**Issue by simanlx** [crazecoder/flutter_luban#18]
Compiler message:
../../../Desktop/flutter/.pub-cache/hosted/pub.flutter-io.cn/zoomable_image-1.3.1/lib/src/zoomable_image.dart:174:30: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('../../../Desktop/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('../../../Desktop/flutter/packages/flutter/lib/src/painting/image_stream.dart').
    _imageStream.addListener(_handleImageLoaded);
                             ^
../../../Desktop/flutter/.pub-cache/hosted/pub.flutter-io.cn/zoomable_image-1.3.1/lib/src/zoomable_image.dart:186:33: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('../../../Desktop/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('../../../Desktop/flutter/packages/flutter/lib/src/painting/image_stream.dart').
    _imageStream.removeListener(_handleImageLoaded);
                                ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
Failed to build bundle.
Error launching application on iPhone 11 Pro Max.

**Comment by crazecoder** [comment]
这里没有看到luban库相关的报错信息，更像是zoomable_image和flutter的冲突
