### ISSUE TITLE
咋压缩之后图片纵横比例变了

### ISSUE THREAD

**Issue by hicodo** [crazecoder/flutter_luban#2]

**Comment by crazecoder** [comment]
方便把图片发给我看看吗

**Comment by jlcool** [comment]
image 插件的问题，我这也宽高反了，无法使用，麻烦优化下吧 @crazecoder

**Comment by terryyhl** [comment]
先用这个FlutterNativeImage过渡下吧。这个组件目前来看是有这个问题。横拍的照片，压缩完后就竖比例也不对了

**Comment by crazecoder** [comment]
你们的拍照比例是多少，这边4:3和16:9都没问题

**Comment by dmskys** [comment]
拍照拍的是竖屏，最后压缩成了横屏的照片。。。麻烦优化下
如下：
[  == ]
[ ==  ]
[ == ]
压缩后变成了：
[ ===== ]
[ ===== ]

**Comment by crazecoder** [comment]
#15
