### ISSUE TITLE
压缩时间比较长  需要十几秒

### ISSUE THREAD

**Issue by liuzeze** [crazecoder/flutter_luban#3]
不知道是不是我的代码有问题,  图片是 1920*1080的屏幕截图
` 
Future getImage() async {
    await ImagePicker.pickImage(source: ImageSource.gallery).then((file) async {
      CompressObject compressObject = CompressObject(
        imageFile: file,
        //image
        path: file.parent.absolute.path,
      );
      return Luban.compressImage(compressObject);
    }).then((_path) {
      setState(() {
        imgUrlList.clear();
        imgUrlList.add(_path);
      });
    });
  }`

**Comment by crazecoder** [comment]
压缩慢的问题，只能等待底层image去解决
